FILE = patch_add_copy_backupimage_after_ota.patch

all:
	@echo "Finding the file $(wildcard $(FILE)) ..."
ifeq ($(FILE), $(wildcard $(FILE)))
	@echo "Fild the file!!"
else
	@echo "Can't find the file!"
endif
